[package]
name = "rustbac-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rustbac-core = { path = "../rustbac-core" }
rustbac-datalink = { path = "../rustbac-datalink" }
rustbac-bacnet-sc = { path = "../rustbac-bacnet-sc" }
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
