[package]
name = "rustbac-datalink"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rustbac-core = { path = "../rustbac-core" }
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
